//Table for ISRs error codes

.global isr0   // Divide By Zero Exception
.global isr1   // Debug Exception
.global isr2   // Non Maskable Interrupt Exception
.global isr3   // Int 3 Exception
.global isr4   // INTO Exception
.global isr5   // Out of Bounds Exception
.global isr6   // Invalid Opcode Exception
.global isr7   // Coprocessor Not Available Exception
.global isr8   // Double Fault Exception (With Error Code!)
.global isr9   // Coprocessor Segment Overrun Exception
.global isr10  // Bad TSS Exception (With Error Code!)
.global isr11  // Segment Not Present Exception (With Error Code!)
.global isr12  // Stack Fault Exception (With Error Code!)
.global isr13  // General Protection Fault Exception (With Error Code!)
.global isr14  // Page Fault Exception (With Error Code!)
.global isr15  // Reserved Exception
.global isr16  // Floating Point Exception
.global isr17  // Alignment Check Exception
.global isr18  // Machine Check Exception
.global isr19  // Reserved
.global isr20  // Reserved
.global isr21  // Reserved
.global isr22  // Reserved
.global isr23  // Reserved
.global isr24  // Reserved
.global isr25  // Reserved
.global isr26  // Reserved
.global isr27  // Reserved
.global isr28  // Reserved
.global isr29  // Reserved
.global isr30  // Reserved
.global isr31  // Reserved


