//Table for ISRs error codes

.global irq0
.global irq1
.global irq2
.global irq3
.global irq4
.global irq5
.global irq6
.global irq7
.global irq8
.global irq9
.global irq10
.global irq11
.global irq12
.global irq13
.global irq14
.global irq15
/*
irq0:
    cli
    pushl $0
    pushl $32
    jmp irq_common_stub

irq1:
    cli
    pushl $0
    pushl $33
    jmp irq_common_stub

irq2:
    cli
    pushl $0
    pushl $34
    jmp irq_common_stub

irq3:
    cli
    pushl $0
    pushl $35
    jmp irq_common_stub

irq4:
    cli
    pushl $0
    pushl $36
    jmp irq_common_stub

irq5:
    cli
    pushl $0
    pushl $37
    jmp irq_common_stub


irq6:
    cli
    pushl $0
    pushl $38
    jmp irq_common_stub

irq7:
    cli
    pushl $0
    pushl $39
    jmp irq_common_stub

irq8:
    cli
    pushl $0
    pushl $40
    jmp irq_common_stub

irq9:
    cli
    pushl $0
    pushl $41
    jmp irq_common_stub

irq10:
    cli
    pushl $0
    pushl $42
    jmp irq_common_stub

irq11:
    cli
    pushl $0
    pushl $43
    jmp irq_common_stub

irq12:
    cli
    pushl $0
    pushl $44
    jmp irq_common_stub

irq13:
    cli
    pushl $0
    pushl $45
    jmp irq_common_stub

irq14:
    cli
    pushl $0
    pushl $46
    jmp irq_common_stub

irq15:
    cli
    pushl $0
    pushl $47
    jmp irq_common_stub
*/
